const people=[{name:'Zendaya',meta:'Actor · USA',query:'Zendaya'},{name:'Margot Robbie',meta:'Actor · Australia',query:'Margot Robbie'},{name:'Ana de Armas',meta:'Actor · Cuba',query:'Ana de Armas'},{name:'Rihanna',meta:'Musician · Barbados',query:'Rihanna'},{name:'Sydney Sweeney',meta:'Actor · USA',query:'Sydney Sweeney'},{name:'Dua Lipa',meta:'Musician · UK',query:'Dua Lipa'}];
const metrics=['Face','Eyes','Body shape','Ass','Boobs','Sex appeal','Perceived personality'];
let personIndex=0,metricIndex=0,scores=Object.fromEntries(metrics.map(m=>[m,7])),images={};
const $=s=>document.querySelector(s);
function average(){return metrics.reduce((n,m)=>n+scores[m],0)/metrics.length}
function fallback(){return 'linear-gradient(135deg,#dedee2,#a5a7ae)'}
function renderSlider(){const s=$('#scoreSlider'),v=scores[metrics[metricIndex]];s.value=v;s.style.setProperty('--score-pct',`${((v-1)/9)*100}%`);$('#markValue').textContent=v;s.setAttribute('aria-label',`${metrics[metricIndex]} score: ${v} out of 10`)}
function renderMetric(){const m=metrics[metricIndex];$('#stepCount').textContent=`${metricIndex+1} of ${metrics.length}`;$('#metricNumber').textContent=`${String(metricIndex+1).padStart(2,'0')} · RATING`;$('#rateTitle').textContent=m;$('#rateQuestion').textContent=`What’s your rating for her ${m.toLowerCase()}?`;$('#progressBar').style.width=`${((metricIndex+1)/metrics.length)*100}%`;$('#continueButton').firstChild.textContent=metricIndex===metrics.length-1?'Review rating ':'Next ';renderSlider()}
async function fetchImage(query){if(images[query])return images[query];try{const r=await fetch(`https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(query)}&gsrnamespace=6&gsrlimit=10&prop=imageinfo&iiprop=url&iiurlwidth=1000&format=json&origin=*`);const d=await r.json();const url=Object.values(d.query?.pages||{}).map(x=>x.imageinfo?.[0]?.thumburl||x.imageinfo?.[0]?.url).find(Boolean);if(url){images[query]=url;return url}}catch(e){console.warn(e)}return ''}
async function renderPerson(){const p=people[personIndex],el=$('#portraitImage');el.style.opacity=0;$('#celebrityName').textContent=p.name;$('#celebrityMeta').textContent=p.meta;$('#startRating').firstChild.textContent=`Rate ${p.name} `;const src=await fetchImage(p.query);if(people[personIndex]!==p)return;p.image=src;el.style.backgroundImage=src?`url("${src}")`:fallback();el.style.opacity=1;$('#imageStatus').textContent=src?'Wikimedia Commons image':'Image unavailable'}
function getRatings(){return JSON.parse(localStorage.getItem('velvet-score-ratings')||'[]')}
function renderReview(){const p=people[personIndex];$('#reviewName').textContent=p.name;$('#reviewOverall').textContent=average().toFixed(1);$('#reviewList').innerHTML=metrics.map((m,i)=>`<div class="review-row"><button data-edit="${i}"><span>${String(i+1).padStart(2,'0')}</span>${m}</button><strong>${scores[m]}/10</strong></div>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>{metricIndex=Number(b.dataset.edit);showView('rate');renderMetric()}))}
function renderBoard(){const list=getRatings().sort((a,b)=>b.score-a.score);$('#ratedCount').textContent=list.length;$('#averageScore').textContent=list.length?(list.reduce((n,x)=>n+x.score,0)/list.length).toFixed(1):'—';$('#emptyBoard').style.display=list.length?'none':'block';$('#leaderboard').innerHTML=list.map((x,i)=>`<article class="leader-row"><span class="rank">${String(i+1).padStart(2,'0')}</span><div class="thumb" style="${x.image?`background-image:url('${x.image}')`:`background:${fallback()}`}"></div><div><div class="leader-name">${x.name}</div><div class="leader-meta">Updated ${new Date(x.updatedAt).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</div></div><strong class="leader-score">${x.score}</strong></article>`).join('')}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`).classList.add('active');if(name==='review')renderReview();if(name==='board')renderBoard();window.scrollTo(0,0)}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)}
$('#startRating').addEventListener('click',()=>{metricIndex=0;showView('rate');renderMetric()});$('#backToDiscover').addEventListener('click',()=>showView('discover'));$('#skipMetric').addEventListener('click',()=>{scores[metrics[metricIndex]]=7;if(metricIndex===metrics.length-1)showView('review');else{metricIndex++;renderMetric()}});$('#scoreSlider').addEventListener('input',e=>{scores[metrics[metricIndex]]=Number(e.target.value);renderSlider()});$('#continueButton').addEventListener('click',()=>{if(metricIndex===metrics.length-1)showView('review');else{metricIndex++;renderMetric()}});$('#skipSubject').addEventListener('click',()=>{personIndex=(personIndex+1)%people.length;metricIndex=0;scores=Object.fromEntries(metrics.map(m=>[m,7]));renderPerson()});$('#fileScore').addEventListener('click',()=>{const p=people[personIndex],list=getRatings().filter(x=>x.name!==p.name);list.push({name:p.name,meta:p.meta,image:p.image||'',score:Number(average().toFixed(1)),metrics:{...scores},updatedAt:new Date().toISOString()});localStorage.setItem('velvet-score-ratings',JSON.stringify(list));toast('Rating saved');personIndex=(personIndex+1)%people.length;metricIndex=0;scores=Object.fromEntries(metrics.map(m=>[m,7]));showView('discover');renderPerson()});document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.go)));$('#clearBoard').addEventListener('click',()=>{if(confirm('Clear all private ratings?')){localStorage.removeItem('velvet-score-ratings');renderBoard();toast('Ratings cleared')}});renderPerson();